apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: welcome
        image: 20152282/jenkins-welcome-app:cdd2ef4:548b4ba
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: welcome-svc
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
  - port: 8000
    targetPort: 8080

